// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "haven_types.h"
#include <Rcpp.h>

using namespace Rcpp;

// df_parse_sas
List df_parse_sas(const std::string& b7dat, const std::string& b7cat);
RcppExport SEXP haven_df_parse_sas(SEXP b7datSEXP, SEXP b7catSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const std::string& >::type b7dat(b7datSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type b7cat(b7catSEXP);
    __result = Rcpp::wrap(df_parse_sas(b7dat, b7cat));
    return __result;
END_RCPP
}
// df_parse_dta
List df_parse_dta(std::string filename);
RcppExport SEXP haven_df_parse_dta(SEXP filenameSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type filename(filenameSEXP);
    __result = Rcpp::wrap(df_parse_dta(filename));
    return __result;
END_RCPP
}
// df_parse_por
List df_parse_por(std::string filename);
RcppExport SEXP haven_df_parse_por(SEXP filenameSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type filename(filenameSEXP);
    __result = Rcpp::wrap(df_parse_por(filename));
    return __result;
END_RCPP
}
// df_parse_sav
List df_parse_sav(std::string filename);
RcppExport SEXP haven_df_parse_sav(SEXP filenameSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type filename(filenameSEXP);
    __result = Rcpp::wrap(df_parse_sav(filename));
    return __result;
END_RCPP
}
// write_sav
void write_sav(List data, std::string path);
RcppExport SEXP haven_write_sav(SEXP dataSEXP, SEXP pathSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< List >::type data(dataSEXP);
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    write_sav(data, path);
    return R_NilValue;
END_RCPP
}
// write_dta
void write_dta(List data, std::string path);
RcppExport SEXP haven_write_dta(SEXP dataSEXP, SEXP pathSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< List >::type data(dataSEXP);
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    write_dta(data, path);
    return R_NilValue;
END_RCPP
}
