# Generated by cpp11: do not edit by hand

df_parse_sas <- function(spec_b7dat, spec_b7cat, encoding, catalog_encoding, cols_skip, n_max, rows_skip) {
  .Call(`_haven_df_parse_sas`, spec_b7dat, spec_b7cat, encoding, catalog_encoding, cols_skip, n_max, rows_skip)
}

df_parse_xpt <- function(spec, cols_skip, n_max, rows_skip) {
  .Call(`_haven_df_parse_xpt`, spec, cols_skip, n_max, rows_skip)
}

df_parse_dta <- function(spec, encoding, cols_skip, n_max, rows_skip) {
  .Call(`_haven_df_parse_dta`, spec, encoding, cols_skip, n_max, rows_skip)
}

df_parse_sav <- function(spec, encoding, user_na, cols_skip, n_max, rows_skip) {
  .Call(`_haven_df_parse_sav`, spec, encoding, user_na, cols_skip, n_max, rows_skip)
}

df_parse_por <- function(spec, encoding, user_na, cols_skip, n_max, rows_skip) {
  .Call(`_haven_df_parse_por`, spec, encoding, user_na, cols_skip, n_max, rows_skip)
}

write_sav_ <- function(data, path, compress) {
  invisible(.Call(`_haven_write_sav_`, data, path, compress))
}

write_dta_ <- function(data, path, version, label, strl_threshold) {
  invisible(.Call(`_haven_write_dta_`, data, path, version, label, strl_threshold))
}

write_sas_ <- function(data, path) {
  invisible(.Call(`_haven_write_sas_`, data, path))
}

write_xpt_ <- function(data, path, version, name, label) {
  invisible(.Call(`_haven_write_xpt_`, data, path, version, name, label))
}
