# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

df_parse_sas <- function(b7dat, b7cat, normalise_na) {
    .Call('haven_df_parse_sas', PACKAGE = 'haven', b7dat, b7cat, normalise_na)
}

df_parse_dta <- function(filename, normalise_na) {
    .Call('haven_df_parse_dta', PACKAGE = 'haven', filename, normalise_na)
}

df_parse_por <- function(filename, normalise_na) {
    .Call('haven_df_parse_por', PACKAGE = 'haven', filename, normalise_na)
}

df_parse_sav <- function(filename, normalise_na) {
    .Call('haven_df_parse_sav', PACKAGE = 'haven', filename, normalise_na)
}

write_sav_ <- function(data, path) {
    invisible(.Call('haven_write_sav_', PACKAGE = 'haven', data, path))
}

write_dta_ <- function(data, path) {
    invisible(.Call('haven_write_dta_', PACKAGE = 'haven', data, path))
}

